-- Supabase Storage Setup Notes
-- Bucket name: myshillong-media
-- Recommended folders:
-- vendors/{vendor_id}/cover/
-- vendors/{vendor_id}/gallery/
-- vendors/{vendor_id}/menu/
-- deals/{deal_id}/
-- categories/
-- ads/
-- branding/
--
-- Suggested bucket policy:
-- 1) Admin-authenticated uploads via dashboard.
-- 2) Public read only for approved objects used in public views.
