/* eslint-disable @typescript-eslint/no-explicit-any */
import { FormSection } from './FormSection';

export function VendorForm({ action, vendor, localities }: { action: (formData: FormData)=>void | Promise<void>; vendor?: any; localities: any[]; categories: any[]; subcategories: any[] }) {
  return <div className="space-y-4"><h1 className="text-2xl font-semibold">{vendor ? 'Edit Vendor' : 'New Vendor'}</h1><form action={action} className="space-y-4">{vendor?.id ? <input type="hidden" name="id" defaultValue={vendor.id} /> : null}
    <FormSection title="Basic Info"><div className="grid gap-2 md:grid-cols-2"><input name="name" defaultValue={vendor?.name} placeholder="Business name" className="rounded border px-3 py-2" required/><input name="slug" defaultValue={vendor?.slug} placeholder="slug" className="rounded border px-3 py-2"/><input name="short_description" defaultValue={vendor?.short_description} placeholder="Short description" className="rounded border px-3 py-2 md:col-span-2"/><textarea name="full_description" defaultValue={vendor?.full_description} placeholder="Full description" className="rounded border px-3 py-2 md:col-span-2"/></div></FormSection>
    <FormSection title="Contact"><div className="grid gap-2 md:grid-cols-2">{['owner_name','owner_phone','owner_email','public_phone','whatsapp','public_email','website_url','instagram_url','facebook_url'].map((f)=><input key={f} name={f} defaultValue={vendor?.[f]} placeholder={f} className="rounded border px-3 py-2" />)}</div></FormSection>
    <FormSection title="Location"><div className="grid gap-2 md:grid-cols-2"><select name="locality_id" defaultValue={vendor?.locality_id} className="rounded border px-3 py-2"><option value="">Select locality</option>{localities.map((l)=><option key={l.id} value={l.id}>{l.name}</option>)}</select>{['address','landmark','latitude','longitude'].map((f)=><input key={f} name={f} defaultValue={vendor?.[f]} placeholder={f} className="rounded border px-3 py-2"/>)}</div></FormSection>
    <FormSection title="Media & Visibility"><div className="grid gap-2 md:grid-cols-2">{['cover_image_path','gallery_image_paths','tags','search_keywords','price_range','priority'].map((f)=><input key={f} name={f} defaultValue={Array.isArray(vendor?.[f]) ? vendor[f].join(', ') : vendor?.[f]} placeholder={f} className="rounded border px-3 py-2"/>)}<select name="status" defaultValue={vendor?.status ?? 'pending'} className="rounded border px-3 py-2"><option value="pending">pending</option><option value="active">active</option><option value="inactive">inactive</option><option value="rejected">rejected</option></select><label><input type="checkbox" name="is_verified" defaultChecked={vendor?.is_verified}/> Verified</label><label><input type="checkbox" name="is_featured" defaultChecked={vendor?.is_featured}/> Featured</label></div></FormSection>
    <FormSection title="Food Details"><div className="text-xs text-slate-600">Food/Fashion profile rows can be managed after vendor creation in dedicated profile CRUD extension.</div></FormSection>
    <FormSection title="Admin Notes"><textarea name="internal_notes" defaultValue={vendor?.internal_notes} className="w-full rounded border px-3 py-2"/></FormSection>
    <button className="rounded bg-sky-600 px-4 py-2 text-white">Save Vendor</button>
  </form></div>;
}
